# ---
# deployment:
#   tasks:
#     - export DEPLOYPATH=/home/stormsco/SGH
#     - /bin/cp -R * $DEPLOYPATH
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/stormsco/SGH/
    - /bin/cp -r * $DEPLOYPATH #copy all from root
    #    - /bin/cp -r ./public/* $DEPLOYPATH/public_html/
    - /bin/cp ./public/articleImages/* /home/stormsco/public_html/new_sgh_public/articleImages
    - /bin/cp ./public/assets/* /home/stormsco/public_html/new_sgh_public/assets
    - /bin/cp ./public/assets2/* /home/stormsco/public_html/new_sgh_public/assets2
    - /bin/cp ./public/client/* /home/stormsco/public_html/new_sgh_public/client
    - /bin/cp ./public/css/* /home/stormsco/public_html/new_sgh_public/css
    - /bin/cp ./public/dist/* /home/stormsco/public_html/new_sgh_public/dist
    - /bin/cp ./public/js/* /home/stormsco/public_html/new_sgh_public/js
